language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"

install: pip install . tox

script: tox

deploy:
    # production pypi
  - provider: pypi
    distributions: sdist
    user: "michaelimfeld"
    password:
      secure: "JHwTohwQH6Kpyw6hdaiTebfeMYyQJjlcfgpPfU8t/xj7LGYKJjlB6r4/OkOXeFmROn2rnpapbauTM8cRvTWQmJxkUXHC1wWLLHCotmsriHARUNcubU/JRzeasMVjpjBGF40+tIsgbOQt2Ol0MkUWThOq49hGiLth//bj4ylCG7igB448ZbAjFiTCk50d77KJ/16FN74MJjVQ2yHbdKio9xukSa94UWIYPoKSVhAi9TOhgJNLYmmJyiIhiUNIbfB86fvF2DrK7kXDzSLlO98nAhPawEzRj33pNUg4bpS6rPRB7yZ7R1AHQulIHvoKUqZypmgzZ5wFPdoEC40a+sG/tKgaMrRNqDY2fSiucaLa6okRze8AIGE2EpsPlRBKjvtIG9DBttrCcoaU8oZ1/D68dnIS5fZp5oZWQeIuLsf/SrRX8rRNQSLZKqIlX2Cgngqq/8+6c3oqt5jHQNJ1csj5esMuIr1rqd9dd/Q4+fMOiT1225jD3Q22fUbT9wjhsbS/RpuH6A/Zy0yUs/YV+DjmRipr/iU+PZTL4Kkv94Cxg2ad0zpQk51yMLEt2fAuxHsGhgVqIJ/msPpuU0OrLdTuAZ852JxELUIkKricnJO/nsuCGOZsqiTi/fayG3jucL9KSQ0ewWKmPZxWjnRILpNBFpcuuV5kUTkrGbl7Ndl6ewY="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
